name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -ldflags="-extldflags=-static" -tags sqlite_omit_load_extension,osusergo,netgo

    - name: Test
      run: go test -v -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Codecov
      uses: codecov/codecov-action@v2.0.2

    - name: golint
      run: |
        go env
        go get golang.org/x/lint/golint
        go install golang.org/x/lint/golint
        golint ./...
   
    - name: vet
      run: go vet ./...

    - name: Build Docker image
      uses: docker/build-push-action@v2.7.0
      with:
        push: false

